sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

before_script:
- npm install -g angular-cli
- npm install

script:
- ng build

notifications:
  slack: optimusinformation:7XhylGt33hYxi9fTsvtQeiGd

deploy:
  provider: releases
  api_key: "0ab818e2e7a7c8e44c74c2d5c70fa30faf6ea57a"
  file: "build"
  skip_cleanup: true
  on:
    tags: true
