sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

branches:
  except:
    - /^build-[0-9a-z\-]*/
script:
- npm install jquery
after_success:

  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.name $GITHUB_USER
  - export MAJOR_VERSION=1
  - export GIT_TAG=v$MAJOR_VERSION.$TRAVIS_JOB_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER on $(date -u "+%Y-%m-%d-%H-%M")-"
  - git push https://$GITHUB_USER:$GITHUB_PASS@github.com//varung-optimus/demo-ng2-travis-integration $GIT_TAG
