sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

branches:
  except:
    - /^build-[0-9a-z\-]*/
script:
- npm install -g angular-cli
after_success:
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push https://varung-optimus/demo-ng2-travis-integration $GIT_TAG
